plugins {
    id 'com.android.library'
}
apply from: "${rootProject.projectDir}/gradle/base-android-config.gradle"

android {
    namespace 'com.moove.analytics'
}

dependencies {
    implementation project(':core')

    api libs.herald.core
    implementation libs.herald.log
    implementation libs.herald.firebase
    implementation libs.herald.mixpanel
    implementation libs.herald.adjust

    implementation libs.bundles.koin

    testImplementation libs.bundles.tests.unit
    testImplementation libs.herald.testing
}
