name: Job set up
description: Sets up the Java and Gradle
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
